//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batteristatistikview
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string dateOfImplantation { get; set; }
        public string pacemakerSerialNumber { get; set; }
        public int estimatedDaysOfServiceLeft { get; set; }
    }
}
