//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class linktransmissionepisode
    {
        public int ID { get; set; }
        public int transmissionID { get; set; }
        public int episodeID { get; set; }
        public string episodeDate { get; set; }
    }
}
