//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pacemakerdataEntities : DbContext
    {
        public pacemakerdataEntities()
            : base("name=pacemakerdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<pacemakerdataview> pacemakerdataview { get; set; }
        public DbSet<batteristatistikview> batteristatistikview { get; set; }
        public DbSet<linktransmissionepisode> linktransmissionepisode { get; set; }
        public DbSet<tblepisodetype> tblepisodetype { get; set; }
        public DbSet<tblpacemakerunit> tblpacemakerunit { get; set; }
        public DbSet<tblpatient> tblpatient { get; set; }
        public DbSet<tbltransmission> tbltransmission { get; set; }
        public DbSet<tblpacemakerunittype> tblpacemakerunittype { get; set; }
    }
}
