//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltransmission
    {
        public int ID { get; set; }
        public int patientID { get; set; }
        public string transmissionDate { get; set; }
        public int PMBatteryPercent { get; set; }
    }
}
